// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/kingzcheung/tinyurl/config"
	"github.com/kingzcheung/tinyurl/handler/api"
	"github.com/kingzcheung/tinyurl/handler/auth"
	"github.com/kingzcheung/tinyurl/handler/web"
	"github.com/kingzcheung/tinyurl/store/url"
	"github.com/kingzcheung/tinyurl/store/user"
)

// Injectors from wire.go:

func InitializeApp(config2 *config.Config) (*app, error) {
	db, err := provideDb(config2)
	if err != nil {
		return nil, err
	}
	urlStore := url.NewUrlStore(db)
	userStore := user.NewUserStore(db)
	hashID, err := providerHashIds(config2)
	if err != nil {
		return nil, err
	}
	server := api.NewServer(urlStore, userStore, hashID)
	health := healthProvide()
	group := provideUrlCache(urlStore)
	webServer := web.NewServer(group, config2)
	sessionManager, err := provideSession(config2, db)
	if err != nil {
		return nil, err
	}
	authServer := auth.NewServer(userStore, sessionManager, config2)
	mux := provideRouter(server, health, webServer, authServer)
	httpServer := provideServer(mux, config2, sessionManager)
	mainApp := newApp(config2, httpServer)
	return mainApp, nil
}
